language: node_js
script: karma start spec/jasmine/karma.conf.js --single-run
node_js:
- "node"

before_script:
  - cd ./nodejs

script:  
- npm install
- npm run postinstall

before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
