language: node_js
script:
- karma start spec/jasmine/karma.conf.js --single-run
- npx cypress run 

install:
  - npm ci

node_js:
- "10.14.1"

before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
